version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: app
  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    links:
      - mongo
    volumes:
      - './app:/usr/src/app/app'
    environment:
      DB_USER: root
      DB_PASS: password
      DB_NAME: app
      DB_HOST: mongo
      HOST: 0.0.0.0